const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.sliderbar,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Clipboard,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Button.Cnds.IsChecked,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.sliderbar.Exps.Maximum,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SnapshotCanvas
	];
};
self.C3_JsPropNameTable = [
	{LienzoDeDibujo: 0},
	{Teclado: 0},
	{Mouse: 0},
	{ControlTáctil: 0},
	{slider_grosor: 0},
	{texto_grosor: 0},
	{box_dibujar: 0},
	{slider_red: 0},
	{slider_green: 0},
	{slider_blue: 0},
	{btn_red: 0},
	{sprite_red: 0},
	{btn_green: 0},
	{btn_blue: 0},
	{btn_color: 0},
	{texto_color: 0},
	{tinta: 0},
	{ArrastrarYSoltar: 0},
	{RestringidoA: 0},
	{borrador: 0},
	{box_borrar: 0},
	{btn_capturar: 0},
	{Portapapeles: 0},
	{marco: 0},
	{grosor_linea: 0},
	{x1_trazo: 0},
	{y1_trazo: 0},
	{x2_trazo: 0},
	{y2_trazo: 0},
	{intervalo_trazo: 0},
	{red: 0},
	{green: 0},
	{blue: 0}
];

self.InstanceType = {
	LienzoDeDibujo: class extends self.IDrawingCanvasInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	ControlTáctil: class extends self.IInstance {},
	slider_grosor: class extends self.ISliderBarInstance {},
	texto_grosor: class extends self.ITextInstance {},
	box_dibujar: class extends self.IButtonInstance {},
	slider_red: class extends self.ISliderBarInstance {},
	slider_green: class extends self.ISliderBarInstance {},
	slider_blue: class extends self.ISliderBarInstance {},
	btn_red: class extends self.IButtonInstance {},
	sprite_red: class extends self.ISpriteInstance {},
	btn_green: class extends self.IButtonInstance {},
	btn_blue: class extends self.IButtonInstance {},
	btn_color: class extends self.IButtonInstance {},
	texto_color: class extends self.ITextInstance {},
	tinta: class extends self.ISpriteInstance {},
	borrador: class extends self.ISpriteInstance {},
	box_borrar: class extends self.IButtonInstance {},
	btn_capturar: class extends self.IButtonInstance {},
	Portapapeles: class extends self.IInstance {},
	marco: class extends self.ISpriteInstance {}
}